source 'http://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'haml'
gem 'sinatra-reloader'
gem 'sinatra-sugar'
gem 'sinatra-advanced-routes'
gem 'sinatra-static-assets'
gem 'sinatra-content-for'
gem 'json'
